---
apiVersion: v1
kind: Pod
metadata:
  name: k8s-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: gcr.io/google_containers/hyperkube-amd64:v1.5.2
    command:
    - /hyperkube
    - proxy
    - --master=https://54.154.201.60:8443
    - --kubeconfig=/etc/kubernetes/ssl/worker-kubeconfig.yaml
    - --proxy-mode=iptables
    securityContext:
      privileged: true
    volumeMounts:
    - name: kubernetes-ssl
      mountPath: /etc/kubernetes/ssl
  volumes:
  - name: kubernetes-ssl
    hostPath:
      path: /opt/kubernetes/ssl
      readOnly: true
