#!/bin/bash
echo "REPO_PATH: '$REPO_PATH'"
echo "REPO_HTTPS: '$REPO_HTTPS'"
echo "WORKSPACE: '$WORKSPACE'"
echo "DOCKER_NAME_LABEL: '$DOCKER_NAME_LABEL'"
git clone $REPO_HTTPS $WORKSPACE
pushd $WORKSPACE/$REPO_PATH
    docker build -t=$DOCKER_NAME_LABEL .
popd
