---
apiVersion: v1
kind: Pod
metadata:
  name: k8s-api
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: apiserver
    image: gcr.io/google_containers/hyperkube-amd64:v1.5.2
    command:
    - "/hyperkube"
    - apiserver
    - "--service-cluster-ip-range=10.0.0.1/24"
    - "--secure-port=8443"
    - "--etcd-servers=http://127.0.0.1:2379"
    - "--admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota"
    - "--min-request-timeout=300"
    - "--tls-cert-file=/etc/kubernetes/ssl/apiserver.pem"
    - "--tls-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem"
    - "--client-ca-file=/etc/kubernetes/ssl/ca.pem"
    - "--service-account-key-file=/etc/kubernetes/ssl/apiserver-key.pem"
    - "--token-auth-file=/etc/kubernetes/ssl/token.csv"
    - "--allow-privileged=true"
    - "--v=2"
    volumeMounts:
    - name: kubernetes-ssl
      mountPath: /etc/kubernetes/ssl
  volumes:
  - name: kubernetes-ssl
    hostPath:
      path: /opt/kubernetes/ssl
      readOnly: true
