---
apiVersion: v1
kind: Pod
metadata:
  name: k8s-controller
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: controller-manager
    image: gcr.io/google_containers/hyperkube-amd64:v1.5.2
    command:
    - "/hyperkube"
    - controller-manager
    - "--master=127.0.0.1:8080"
    - "--service-account-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem"
    - "--root-ca-file=/etc/kubernetes/ssl/ca.pem"
    - "--min-resync-period=3m"
    - "--leader-elect=true"
    - "--cluster-cidr=10.1.0.0/16"
    - "--v=2"
    volumeMounts:
    - name: kubernetes-ssl
      mountPath: /etc/kubernetes/ssl
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10252
      initialDelaySeconds: 15
      timeoutSeconds: 1
  volumes:
  - name: kubernetes-ssl
    hostPath:
      path: /opt/kubernetes/ssl
      readOnly: true
