---
apiVersion: v1
kind: Pod
metadata:
  name: k8s-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: gcr.io/google_containers/hyperkube-amd64:v1.6.1
    command:
    - /hyperkube
    - proxy
    - --master=http://127.0.0.1:8080
    - --cluster-cidr=172.16.0.0/16
    - --proxy-mode=iptables
    - --v=2
    securityContext:
      privileged: true
