---
apiVersion: v1
kind: Pod
metadata:
  name: k8s-scheduler
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: scheduler
    image: gcr.io/google_containers/hyperkube-amd64:v1.7.2
    command:
    - "/hyperkube"
    - scheduler
    - "--master=127.0.0.1:8080"
    - "--leader-elect=true"
    - "--v=2"
