apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    certificate-authority: /etc/kubernetes/ssl/ca.pem
    server: https://10.0.0.1:443
users:
- name: kubelet
  user:
    client-certificate: /etc/kubernetes/ssl/slave-worker.pem
    client-key: /etc/kubernetes/ssl/slave-worker-key.pem
contexts:
- context:
    cluster: default-cluster
    user: kubelet
  name: kubelet-context
current-context: kubelet-context
